title: Elian Marsault  # Add a space after the period

logo: 1.png # Use a relative path to logo image 

description: Student in Data analysis and Economis

show_downloads: true # Fix spelling

theme: jekyll-theme-minimal 

plugins:
  - jekyll-seo-tag # Add SEO plugin

google_site_verification: "nE-yBDoWCj5TcTXXNcRBPPiJZxpC6pw5dEdeRo6kTCk" # Verify ownership through Search Console  

ðŸ“§ email: elian.marsault@gmail.com
ðŸ“ž phone number: +33651834037
# Allow visitors to contact you

Skills:
<p align="center">
  <a href="https://skillicons.dev">
    <img src="https://skillicons.dev/icons?i=mysql,py,pytorch,pycharm,r,tensorflow&theme=light" />
  </a>
</p>
